apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: skip-initdb-client
spec:
  secretName: skip-initdb-client-tls

  commonName: "skip-initdb-client"
  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - client auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
