apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skip-initdb
  name: skip-initdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skip-initdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: skip-initdb
    spec:
      containers:
      - image: cnpg-i-skip-initdb:latest
        name: cnpg-i-skip-initdb
        ports:
        - containerPort: 9090
          protocol: TCP
        args:
        - plugin
        - --server-cert=/server/tls.crt
        - --server-key=/server/tls.key
        - --client-cert=/client/tls.crt
        - --server-address=:9090
        volumeMounts:
        - mountPath: /server
          name: server
        - mountPath: /client
          name: client
        resources: {}
      volumes:
      - name: server
        secret:
          secretName: skip-initdb-server-tls
      - name: client
        secret:
          secretName: skip-initdb-client-tls
