apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: skip-initdb-server
spec:
  secretName: skip-initdb-server-tls
  commonName: "skip-initdb"
  dnsNames:
    - skip-initdb

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
